### PR TITLE
Fix/Refactor: missing siblingVersion from sibling check

### LINKED ISSUE #781: ReferenceError: siblingVersion is not defined while installing the package
### Environment
node 20.9.0
yarn 1.22.17
vue 3.5.12
vite 5.4.10

### Steps to Reproduce

1. yarn add @sentry/capacitor @sentry/vue --exact
2. error occured

### Expected Result
package is installed

### Actual Result
error /Users/iyong-eun/Desktop/works/ddtalk/codes/docktalk/node_modules/@sentry/capacitor: Command failed.
Exit code: 1
Command: node scripts/check-siblings.js
Arguments:
Directory: /Users/iyong-eun/Desktop/works/ddtalk/codes/docktalk/node_modules/@sentry/capacitor
Output:
/Users/iyong-eun/Desktop/works/ddtalk/codes/docktalk/node_modules/@sentry/capacitor/scripts/check-siblings.js:69
        errorMessages.push("You must specify the version to the package " + installedVersion + ". ( " + installedVersion + "@" + siblingVersion + ")");
                                                                                                                                 ^

ReferenceError: siblingVersion is not defined
    at ValidateSentryPackageParameters (/Users/iyong-eun/Desktop/works/ddtalk/codes/docktalk/node_modules/@sentry/capacitor/scripts/check-siblings.js:69:130)
    at CheckSiblings (/Users/iyong-eun/Desktop/works/ddtalk/codes/docktalk/node_modules/@sentry/capacitor/scripts/check-siblings.js:128:7)
    at Object.<anonymous> (/Users/iyong-eun/Desktop/works/ddtalk/codes/docktalk/node_modules/@sentry/capacitor/scripts/check-siblings.js:158:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

I think the function `ValidateSentryPackageParameters` should be defined in the function `CheckSiblings` or the variable `siblingVersion` should be passed as an argument.

### PR DESCRIPTION
**Pull request by lucas-zimerman**
Main changes: 
- Added the missing parameter on `ValidateSentryPackageParameters` that was causing the issue of #781.
- Added E2E Logs for the follow-up PR that tests the sibling code:  https://github.com/getsentry/sentry-capacitor/pull/795
- Refactored some error messages.
- Added new checks to support newer Yarn/NPM versions

Fixes #781

### CODE REVIEW

File: scripts/check-siblings.js [hunk 1]
```diff
@@ -1,12 +1,18 @@
...
 
 // Filters all Sentry packages but Capacitor, CLI and Wizard.
 const jsonFilter = /\s*\"\@sentry\/(?!capacitor|wizard|cli|typescript|electron)(?<packageName>[a-zA-Z]+)\"\:\s*\"(?<version>.+)\"/;
 
+const IsE2E = env.sentry_e2e == 'true';
+
+function LogE2E(message) {
+  IsE2E && console.log("E2E_TEST: " + message);
+}
+
```
Comment (krystofwoldrich) [inline scripts/check-siblings.js:15]: Let's isolate the fix and remove the E2E test changes from this PR.

Comment (lucas-zimerman) [reply scripts/check-siblings.js]: Sounds good to me, I have removed the e2e logs on https://github.com/getsentry/sentry-capacitor/pull/829/commits/e5640b0f8e5e4caaa9634b35274d6432ab526c9e

**Review by krystofwoldrich — APPROVED** [review]
LG. I think the refactor and message should also be a separate change, but I checked the code and it looks good.
